Task/apps 2953 collaborations api
openlattice/lattice-js pull request #1259
Opened 2021-05-26 22:55 UTC by solomontang

- Add CollaborationsApi
  - addOrganizationsToCollaboration
  - createCollaboration
  - deleteCollaboration
  - getCollaboration
  - getCollaborationDatabaseInfo
  - getCollaborations
  - getCollaborationsIncludingOrganization
  - getProjectedTablesInCollaboration
  - getProjectedTablesInOrganization
  - getProjectionCollaborationsForTables
  - projectTableToCollaboration
  - removeOrganizationsFromCollaboration
  - removeProjectedTableFromCollaboration
  - renameDatabase
- parameters that accept a list of UUIDs can also accept a single UUID

2021-05-27 01:49 UTC, anzioka submitted a review, later dismissed

2021-05-28 00:14 UTC, UnsungHero97 requested changes
I'll update this pull request to match the latest changes here:

https://github.com/openlattice/openlattice/pull/189

2021-06-05 02:29 UTC, UnsungHero97 approved these changes

2021-06-07 16:01 UTC, anzioka approved these changes

2021-06-07 16:04 UTC, giuliacampana approved these changes

2021-06-07 16:09 UTC, merged